### ISSUE TITLE
AssemblyNameReferenceHandler is not persisting changes

### ISSUE THREAD

**Issue by lukaspirkl** [telerik/justdecompile-plugins#3]
Open any assembly and go to references in the tree. Select any reference. Open Reflexil and "Assembly reference" window which is handled by AssemblyNamedReferenceHandler is opened. When I change the version then select different assembly and then select again the previous one, all changes are gone. Also it is not possible to save any changes made in this window.

**Comment by tsviatko** [comment]
This seems to be a problem of Reflexil as such. We are mostly focused on maintaining the infrastructure that connects JustDecompile and Reflexil. Rather unfortunately, we do not have the resources to improve Reflexil itself. 

You could report this issue in the Reflexil repo - https://github.com/sailro/Reflexil/issues. Or you could fix it and send them a pull request. We'll gladly migrate the fix to JustDecompile Reflexil plugin.

**Comment by senatormas** [comment]
No It's not! we dont have such a problem with reflector and reflexil ! ;)

**Comment by tsviatko** [comment]
Sorry about the huge delay. Somehow this issue went under the radar back when we last discussed it  and never reminded of itself ever since.

After some basic research that still looks like Reflexil problem to me. The code that handles this seems to be outside JustDecompile's domain.

Reflector might use different version of Reflexil. What JustDecompile currently uses is 1.8 which is two major releases behind. So, we will definitely update Reflexil to latest major version before investigating the problem further.

**Comment by tsviatko** [comment]
#4 will deal with this. There are some preliminary results already.
