### ISSUE TITLE
JustDecompile.API project is absent

### ISSUE THREAD

**Issue by alexanderkozlenko** [telerik/justdecompile-plugins#6]
JustDecompileAPI solution contains reference to JustDecompile.API project which doesn't exist in the repository

**Comment by tsviatko** [comment]
True that. The assumption is one develops against the currently installed version of JD on their machine and that's where JustDecompile.API comes from. Maintaining all the possible versions of JustDecompile.API to the repo will take quite some of our scarce resources and that's why we chose this approach.
